// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/federation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FederationService_Register_FullMethodName            = "/opsagent.federation.FederationService/Register"
	FederationService_Heartbeat_FullMethodName           = "/opsagent.federation.FederationService/Heartbeat"
	FederationService_ReportMetrics_FullMethodName       = "/opsagent.federation.FederationService/ReportMetrics"
	FederationService_StreamConfigUpdates_FullMethodName = "/opsagent.federation.FederationService/StreamConfigUpdates"
	FederationService_StreamCommands_FullMethodName      = "/opsagent.federation.FederationService/StreamCommands"
	FederationService_ReportCommandResult_FullMethodName = "/opsagent.federation.FederationService/ReportCommandResult"
	FederationService_ReportHealth_FullMethodName        = "/opsagent.federation.FederationService/ReportHealth"
)

// FederationServiceClient is the client API for FederationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FederationServiceClient interface {
	Register(ctx context.Context, in *FedAgentRegistration, opts ...grpc.CallOption) (*FedRegisterResponse, error)
	Heartbeat(ctx context.Context, in *FedHeartbeatRequest, opts ...grpc.CallOption) (*FedHeartbeatResponse, error)
	ReportMetrics(ctx context.Context, in *FedMetricReport, opts ...grpc.CallOption) (*FedMetricAck, error)
	StreamConfigUpdates(ctx context.Context, in *FedConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FedConfigUpdate], error)
	StreamCommands(ctx context.Context, in *FedCommandStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FedCommandRequest], error)
	ReportCommandResult(ctx context.Context, in *FedCommandResult, opts ...grpc.CallOption) (*FedCommandResultAck, error)
	ReportHealth(ctx context.Context, in *FedHealthReport, opts ...grpc.CallOption) (*FedHealthAck, error)
}

type federationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationServiceClient(cc grpc.ClientConnInterface) FederationServiceClient {
	return &federationServiceClient{cc}
}

func (c *federationServiceClient) Register(ctx context.Context, in *FedAgentRegistration, opts ...grpc.CallOption) (*FedRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FedRegisterResponse)
	err := c.cc.Invoke(ctx, FederationService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) Heartbeat(ctx context.Context, in *FedHeartbeatRequest, opts ...grpc.CallOption) (*FedHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FedHeartbeatResponse)
	err := c.cc.Invoke(ctx, FederationService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) ReportMetrics(ctx context.Context, in *FedMetricReport, opts ...grpc.CallOption) (*FedMetricAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FedMetricAck)
	err := c.cc.Invoke(ctx, FederationService_ReportMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) StreamConfigUpdates(ctx context.Context, in *FedConfigStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FedConfigUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FederationService_ServiceDesc.Streams[0], FederationService_StreamConfigUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FedConfigStreamRequest, FedConfigUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_StreamConfigUpdatesClient = grpc.ServerStreamingClient[FedConfigUpdate]

func (c *federationServiceClient) StreamCommands(ctx context.Context, in *FedCommandStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FedCommandRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FederationService_ServiceDesc.Streams[1], FederationService_StreamCommands_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FedCommandStreamRequest, FedCommandRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_StreamCommandsClient = grpc.ServerStreamingClient[FedCommandRequest]

func (c *federationServiceClient) ReportCommandResult(ctx context.Context, in *FedCommandResult, opts ...grpc.CallOption) (*FedCommandResultAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FedCommandResultAck)
	err := c.cc.Invoke(ctx, FederationService_ReportCommandResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) ReportHealth(ctx context.Context, in *FedHealthReport, opts ...grpc.CallOption) (*FedHealthAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FedHealthAck)
	err := c.cc.Invoke(ctx, FederationService_ReportHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederationServiceServer is the server API for FederationService service.
// All implementations must embed UnimplementedFederationServiceServer
// for forward compatibility.
type FederationServiceServer interface {
	Register(context.Context, *FedAgentRegistration) (*FedRegisterResponse, error)
	Heartbeat(context.Context, *FedHeartbeatRequest) (*FedHeartbeatResponse, error)
	ReportMetrics(context.Context, *FedMetricReport) (*FedMetricAck, error)
	StreamConfigUpdates(*FedConfigStreamRequest, grpc.ServerStreamingServer[FedConfigUpdate]) error
	StreamCommands(*FedCommandStreamRequest, grpc.ServerStreamingServer[FedCommandRequest]) error
	ReportCommandResult(context.Context, *FedCommandResult) (*FedCommandResultAck, error)
	ReportHealth(context.Context, *FedHealthReport) (*FedHealthAck, error)
	mustEmbedUnimplementedFederationServiceServer()
}

// UnimplementedFederationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederationServiceServer struct{}

func (UnimplementedFederationServiceServer) Register(context.Context, *FedAgentRegistration) (*FedRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedFederationServiceServer) Heartbeat(context.Context, *FedHeartbeatRequest) (*FedHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedFederationServiceServer) ReportMetrics(context.Context, *FedMetricReport) (*FedMetricAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedFederationServiceServer) StreamConfigUpdates(*FedConfigStreamRequest, grpc.ServerStreamingServer[FedConfigUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamConfigUpdates not implemented")
}
func (UnimplementedFederationServiceServer) StreamCommands(*FedCommandStreamRequest, grpc.ServerStreamingServer[FedCommandRequest]) error {
	return status.Error(codes.Unimplemented, "method StreamCommands not implemented")
}
func (UnimplementedFederationServiceServer) ReportCommandResult(context.Context, *FedCommandResult) (*FedCommandResultAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCommandResult not implemented")
}
func (UnimplementedFederationServiceServer) ReportHealth(context.Context, *FedHealthReport) (*FedHealthAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHealth not implemented")
}
func (UnimplementedFederationServiceServer) mustEmbedUnimplementedFederationServiceServer() {}
func (UnimplementedFederationServiceServer) testEmbeddedByValue()                           {}

// UnsafeFederationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationServiceServer will
// result in compilation errors.
type UnsafeFederationServiceServer interface {
	mustEmbedUnimplementedFederationServiceServer()
}

func RegisterFederationServiceServer(s grpc.ServiceRegistrar, srv FederationServiceServer) {
	// If the following call panics, it indicates UnimplementedFederationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FederationService_ServiceDesc, srv)
}

func _FederationService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FedAgentRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).Register(ctx, req.(*FedAgentRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FedHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).Heartbeat(ctx, req.(*FedHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_ReportMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FedMetricReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).ReportMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_ReportMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).ReportMetrics(ctx, req.(*FedMetricReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_StreamConfigUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FedConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FederationServiceServer).StreamConfigUpdates(m, &grpc.GenericServerStream[FedConfigStreamRequest, FedConfigUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_StreamConfigUpdatesServer = grpc.ServerStreamingServer[FedConfigUpdate]

func _FederationService_StreamCommands_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FedCommandStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FederationServiceServer).StreamCommands(m, &grpc.GenericServerStream[FedCommandStreamRequest, FedCommandRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_StreamCommandsServer = grpc.ServerStreamingServer[FedCommandRequest]

func _FederationService_ReportCommandResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FedCommandResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).ReportCommandResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_ReportCommandResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).ReportCommandResult(ctx, req.(*FedCommandResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_ReportHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FedHealthReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).ReportHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_ReportHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).ReportHealth(ctx, req.(*FedHealthReport))
	}
	return interceptor(ctx, in, info, handler)
}

// FederationService_ServiceDesc is the grpc.ServiceDesc for FederationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FederationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opsagent.federation.FederationService",
	HandlerType: (*FederationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _FederationService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _FederationService_Heartbeat_Handler,
		},
		{
			MethodName: "ReportMetrics",
			Handler:    _FederationService_ReportMetrics_Handler,
		},
		{
			MethodName: "ReportCommandResult",
			Handler:    _FederationService_ReportCommandResult_Handler,
		},
		{
			MethodName: "ReportHealth",
			Handler:    _FederationService_ReportHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConfigUpdates",
			Handler:       _FederationService_StreamConfigUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamCommands",
			Handler:       _FederationService_StreamCommands_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/federation.proto",
}
