// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/federation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMode int32

const (
	AgentMode_MODE_STANDALONE AgentMode = 0
	AgentMode_MODE_HUB        AgentMode = 1
	AgentMode_MODE_LEAF       AgentMode = 2
)

// Enum value maps for AgentMode.
var (
	AgentMode_name = map[int32]string{
		0: "MODE_STANDALONE",
		1: "MODE_HUB",
		2: "MODE_LEAF",
	}
	AgentMode_value = map[string]int32{
		"MODE_STANDALONE": 0,
		"MODE_HUB":        1,
		"MODE_LEAF":       2,
	}
)

func (x AgentMode) Enum() *AgentMode {
	p := new(AgentMode)
	*p = x
	return p
}

func (x AgentMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_federation_proto_enumTypes[0].Descriptor()
}

func (AgentMode) Type() protoreflect.EnumType {
	return &file_proto_federation_proto_enumTypes[0]
}

func (x AgentMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentMode.Descriptor instead.
func (AgentMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{0}
}

type FedAgentRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AutoLabels    map[string]string      `protobuf:"bytes,11,rep,name=auto_labels,json=autoLabels,proto3" json:"auto_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capabilities  []string               `protobuf:"bytes,12,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Mode          AgentMode              `protobuf:"varint,13,opt,name=mode,proto3,enum=opsagent.federation.AgentMode" json:"mode,omitempty"`
	Region        string                 `protobuf:"bytes,14,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedAgentRegistration) Reset() {
	*x = FedAgentRegistration{}
	mi := &file_proto_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedAgentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedAgentRegistration) ProtoMessage() {}

func (x *FedAgentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedAgentRegistration.ProtoReflect.Descriptor instead.
func (*FedAgentRegistration) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{0}
}

func (x *FedAgentRegistration) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FedAgentRegistration) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *FedAgentRegistration) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *FedAgentRegistration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FedAgentRegistration) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *FedAgentRegistration) GetAutoLabels() map[string]string {
	if x != nil {
		return x.AutoLabels
	}
	return nil
}

func (x *FedAgentRegistration) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *FedAgentRegistration) GetMode() AgentMode {
	if x != nil {
		return x.Mode
	}
	return AgentMode_MODE_STANDALONE
}

func (x *FedAgentRegistration) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type FedRegisterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AssignedRegion  string                 `protobuf:"bytes,2,opt,name=assigned_region,json=assignedRegion,proto3" json:"assigned_region,omitempty"`
	AssignedGroups  []string               `protobuf:"bytes,3,rep,name=assigned_groups,json=assignedGroups,proto3" json:"assigned_groups,omitempty"`
	ConfigVersion   string                 `protobuf:"bytes,4,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	InitialConfig   []byte                 `protobuf:"bytes,5,opt,name=initial_config,json=initialConfig,proto3" json:"initial_config,omitempty"`
	RejectionReason string                 `protobuf:"bytes,6,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FedRegisterResponse) Reset() {
	*x = FedRegisterResponse{}
	mi := &file_proto_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedRegisterResponse) ProtoMessage() {}

func (x *FedRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedRegisterResponse.ProtoReflect.Descriptor instead.
func (*FedRegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{1}
}

func (x *FedRegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *FedRegisterResponse) GetAssignedRegion() string {
	if x != nil {
		return x.AssignedRegion
	}
	return ""
}

func (x *FedRegisterResponse) GetAssignedGroups() []string {
	if x != nil {
		return x.AssignedGroups
	}
	return nil
}

func (x *FedRegisterResponse) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *FedRegisterResponse) GetInitialConfig() []byte {
	if x != nil {
		return x.InitialConfig
	}
	return nil
}

func (x *FedRegisterResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type FedHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedHeartbeatRequest) Reset() {
	*x = FedHeartbeatRequest{}
	mi := &file_proto_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedHeartbeatRequest) ProtoMessage() {}

func (x *FedHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*FedHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{2}
}

func (x *FedHeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FedHeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FedHeartbeatRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type FedHeartbeatResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Ok                    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ConfigVersion         string                 `protobuf:"bytes,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	ConfigUpdateAvailable bool                   `protobuf:"varint,3,opt,name=config_update_available,json=configUpdateAvailable,proto3" json:"config_update_available,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FedHeartbeatResponse) Reset() {
	*x = FedHeartbeatResponse{}
	mi := &file_proto_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedHeartbeatResponse) ProtoMessage() {}

func (x *FedHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*FedHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{3}
}

func (x *FedHeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *FedHeartbeatResponse) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *FedHeartbeatResponse) GetConfigUpdateAvailable() bool {
	if x != nil {
		return x.ConfigUpdateAvailable
	}
	return false
}

type FedMetricReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Metrics       []*FedMetric           `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedMetricReport) Reset() {
	*x = FedMetricReport{}
	mi := &file_proto_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedMetricReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedMetricReport) ProtoMessage() {}

func (x *FedMetricReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedMetricReport.ProtoReflect.Descriptor instead.
func (*FedMetricReport) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{4}
}

func (x *FedMetricReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FedMetricReport) GetMetrics() []*FedMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *FedMetricReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type FedMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fields        []*FedField            `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedMetric) Reset() {
	*x = FedMetric{}
	mi := &file_proto_federation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedMetric) ProtoMessage() {}

func (x *FedMetric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedMetric.ProtoReflect.Descriptor instead.
func (*FedMetric) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{5}
}

func (x *FedMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FedMetric) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FedMetric) GetFields() []*FedField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *FedMetric) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type FedField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*FedField_DoubleValue
	//	*FedField_IntValue
	//	*FedField_StringValue
	//	*FedField_BoolValue
	Value         isFedField_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedField) Reset() {
	*x = FedField{}
	mi := &file_proto_federation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedField) ProtoMessage() {}

func (x *FedField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedField.ProtoReflect.Descriptor instead.
func (*FedField) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{6}
}

func (x *FedField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FedField) GetValue() isFedField_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FedField) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*FedField_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *FedField) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*FedField_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *FedField) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*FedField_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FedField) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*FedField_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isFedField_Value interface {
	isFedField_Value()
}

type FedField_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type FedField_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type FedField_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type FedField_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*FedField_DoubleValue) isFedField_Value() {}

func (*FedField_IntValue) isFedField_Value() {}

func (*FedField_StringValue) isFedField_Value() {}

func (*FedField_BoolValue) isFedField_Value() {}

type FedMetricAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ReceivedCount int64                  `protobuf:"varint,2,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedMetricAck) Reset() {
	*x = FedMetricAck{}
	mi := &file_proto_federation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedMetricAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedMetricAck) ProtoMessage() {}

func (x *FedMetricAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedMetricAck.ProtoReflect.Descriptor instead.
func (*FedMetricAck) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{7}
}

func (x *FedMetricAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *FedMetricAck) GetReceivedCount() int64 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

type FedConfigStreamRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CurrentVersion string                 `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FedConfigStreamRequest) Reset() {
	*x = FedConfigStreamRequest{}
	mi := &file_proto_federation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedConfigStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedConfigStreamRequest) ProtoMessage() {}

func (x *FedConfigStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedConfigStreamRequest.ProtoReflect.Descriptor instead.
func (*FedConfigStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{8}
}

func (x *FedConfigStreamRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FedConfigStreamRequest) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

type FedConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion string                 `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	ConfigYaml    []byte                 `protobuf:"bytes,2,opt,name=config_yaml,json=configYaml,proto3" json:"config_yaml,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedConfigUpdate) Reset() {
	*x = FedConfigUpdate{}
	mi := &file_proto_federation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedConfigUpdate) ProtoMessage() {}

func (x *FedConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedConfigUpdate.ProtoReflect.Descriptor instead.
func (*FedConfigUpdate) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{9}
}

func (x *FedConfigUpdate) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *FedConfigUpdate) GetConfigYaml() []byte {
	if x != nil {
		return x.ConfigYaml
	}
	return nil
}

func (x *FedConfigUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FedConfigUpdate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type FedCommandStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedCommandStreamRequest) Reset() {
	*x = FedCommandStreamRequest{}
	mi := &file_proto_federation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedCommandStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedCommandStreamRequest) ProtoMessage() {}

func (x *FedCommandStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedCommandStreamRequest.ProtoReflect.Descriptor instead.
func (*FedCommandStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{10}
}

func (x *FedCommandStreamRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type FedCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommandId      string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FedCommandRequest) Reset() {
	*x = FedCommandRequest{}
	mi := &file_proto_federation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedCommandRequest) ProtoMessage() {}

func (x *FedCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedCommandRequest.ProtoReflect.Descriptor instead.
func (*FedCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{11}
}

func (x *FedCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *FedCommandRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FedCommandRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FedCommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type FedCommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TimedOut      bool                   `protobuf:"varint,7,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedCommandResult) Reset() {
	*x = FedCommandResult{}
	mi := &file_proto_federation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedCommandResult) ProtoMessage() {}

func (x *FedCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedCommandResult.ProtoReflect.Descriptor instead.
func (*FedCommandResult) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{12}
}

func (x *FedCommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *FedCommandResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FedCommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *FedCommandResult) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *FedCommandResult) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *FedCommandResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *FedCommandResult) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

type FedCommandResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedCommandResultAck) Reset() {
	*x = FedCommandResultAck{}
	mi := &file_proto_federation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedCommandResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedCommandResultAck) ProtoMessage() {}

func (x *FedCommandResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedCommandResultAck.ProtoReflect.Descriptor instead.
func (*FedCommandResultAck) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{13}
}

func (x *FedCommandResultAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type FedHealthReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	SubsystemStatus map[string]string      `protobuf:"bytes,3,rep,name=subsystem_status,json=subsystemStatus,proto3" json:"subsystem_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FedHealthReport) Reset() {
	*x = FedHealthReport{}
	mi := &file_proto_federation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedHealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedHealthReport) ProtoMessage() {}

func (x *FedHealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedHealthReport.ProtoReflect.Descriptor instead.
func (*FedHealthReport) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{14}
}

func (x *FedHealthReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FedHealthReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FedHealthReport) GetSubsystemStatus() map[string]string {
	if x != nil {
		return x.SubsystemStatus
	}
	return nil
}

func (x *FedHealthReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type FedHealthAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FedHealthAck) Reset() {
	*x = FedHealthAck{}
	mi := &file_proto_federation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FedHealthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FedHealthAck) ProtoMessage() {}

func (x *FedHealthAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FedHealthAck.ProtoReflect.Descriptor instead.
func (*FedHealthAck) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{15}
}

func (x *FedHealthAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type FederationReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HubId         string                 `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Leaves        []*LeafInfo            `protobuf:"bytes,3,rep,name=leaves,proto3" json:"leaves,omitempty"`
	Groups        []*GroupInfo           `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	Operations    []*OperationStatus     `protobuf:"bytes,5,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederationReport) Reset() {
	*x = FederationReport{}
	mi := &file_proto_federation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationReport) ProtoMessage() {}

func (x *FederationReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationReport.ProtoReflect.Descriptor instead.
func (*FederationReport) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{16}
}

func (x *FederationReport) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *FederationReport) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *FederationReport) GetLeaves() []*LeafInfo {
	if x != nil {
		return x.Leaves
	}
	return nil
}

func (x *FederationReport) GetGroups() []*GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *FederationReport) GetOperations() []*OperationStatus {
	if x != nil {
		return x.Operations
	}
	return nil
}

type LeafInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Groups        []string               `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LastSeen      int64                  `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	ConfigVersion string                 `protobuf:"bytes,6,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeafInfo) Reset() {
	*x = LeafInfo{}
	mi := &file_proto_federation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeafInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafInfo) ProtoMessage() {}

func (x *LeafInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafInfo.ProtoReflect.Descriptor instead.
func (*LeafInfo) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{17}
}

func (x *LeafInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LeafInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *LeafInfo) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *LeafInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LeafInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *LeafInfo) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MemberCount   int32                  `protobuf:"varint,2,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	OnlineCount   int32                  `protobuf:"varint,3,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	MatchCriteria map[string]string      `protobuf:"bytes,4,rep,name=match_criteria,json=matchCriteria,proto3" json:"match_criteria,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_proto_federation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{18}
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GroupInfo) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *GroupInfo) GetMatchCriteria() map[string]string {
	if x != nil {
		return x.MatchCriteria
	}
	return nil
}

type OperationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	TargetGroup   string                 `protobuf:"bytes,3,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	Success       int32                  `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Failed        int32                  `protobuf:"varint,7,opt,name=failed,proto3" json:"failed,omitempty"`
	Pending       int32                  `protobuf:"varint,8,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStatus) Reset() {
	*x = OperationStatus{}
	mi := &file_proto_federation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStatus) ProtoMessage() {}

func (x *OperationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_federation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStatus.ProtoReflect.Descriptor instead.
func (*OperationStatus) Descriptor() ([]byte, []int) {
	return file_proto_federation_proto_rawDescGZIP(), []int{19}
}

func (x *OperationStatus) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationStatus) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OperationStatus) GetTargetGroup() string {
	if x != nil {
		return x.TargetGroup
	}
	return ""
}

func (x *OperationStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OperationStatus) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OperationStatus) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *OperationStatus) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *OperationStatus) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

var File_proto_federation_proto protoreflect.FileDescriptor

const file_proto_federation_proto_rawDesc = "" +
	"\n" +
	"\x16proto/federation.proto\x12\x13opsagent.federation\"\x8c\x04\n" +
	"\x14FedAgentRegistration\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12M\n" +
	"\x06labels\x18\n" +
	" \x03(\v25.opsagent.federation.FedAgentRegistration.LabelsEntryR\x06labels\x12Z\n" +
	"\vauto_labels\x18\v \x03(\v29.opsagent.federation.FedAgentRegistration.AutoLabelsEntryR\n" +
	"autoLabels\x12\"\n" +
	"\fcapabilities\x18\f \x03(\tR\fcapabilities\x122\n" +
	"\x04mode\x18\r \x01(\x0e2\x1e.opsagent.federation.AgentModeR\x04mode\x12\x16\n" +
	"\x06region\x18\x0e \x01(\tR\x06region\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fAutoLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x01\n" +
	"\x13FedRegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12'\n" +
	"\x0fassigned_region\x18\x02 \x01(\tR\x0eassignedRegion\x12'\n" +
	"\x0fassigned_groups\x18\x03 \x03(\tR\x0eassignedGroups\x12%\n" +
	"\x0econfig_version\x18\x04 \x01(\tR\rconfigVersion\x12%\n" +
	"\x0einitial_config\x18\x05 \x01(\fR\rinitialConfig\x12)\n" +
	"\x10rejection_reason\x18\x06 \x01(\tR\x0frejectionReason\"\xd7\x01\n" +
	"\x13FedHeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12L\n" +
	"\x06labels\x18\x03 \x03(\v24.opsagent.federation.FedHeartbeatRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\x14FedHeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\tR\rconfigVersion\x126\n" +
	"\x17config_update_available\x18\x03 \x01(\bR\x15configUpdateAvailable\"\x84\x01\n" +
	"\x0fFedMetricReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ametrics\x18\x02 \x03(\v2\x1e.opsagent.federation.FedMetricR\ametrics\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xf0\x01\n" +
	"\tFedMetric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x04tags\x18\x02 \x03(\v2(.opsagent.federation.FedMetric.TagsEntryR\x04tags\x125\n" +
	"\x06fields\x18\x03 \x03(\v2\x1d.opsagent.federation.FedFieldR\x06fields\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\bFedField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\fdouble_value\x18\x02 \x01(\x01H\x00R\vdoubleValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\"Q\n" +
	"\fFedMetricAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12%\n" +
	"\x0ereceived_count\x18\x02 \x01(\x03R\rreceivedCount\"\\\n" +
	"\x16FedConfigStreamRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\tR\x0ecurrentVersion\"\x8f\x01\n" +
	"\x0fFedConfigUpdate\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\tR\rconfigVersion\x12\x1f\n" +
	"\vconfig_yaml\x18\x02 \x01(\fR\n" +
	"configYaml\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"4\n" +
	"\x17FedCommandStreamRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x89\x01\n" +
	"\x11FedCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\xd7\x01\n" +
	"\x10FedCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\fR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\ttimed_out\x18\a \x01(\bR\btimedOut\"1\n" +
	"\x13FedCommandResultAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x8c\x02\n" +
	"\x0fFedHealthReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12d\n" +
	"\x10subsystem_status\x18\x03 \x03(\v29.opsagent.federation.FedHealthReport.SubsystemStatusEntryR\x0fsubsystemStatus\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x1aB\n" +
	"\x14SubsystemStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1e\n" +
	"\fFedHealthAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xf6\x01\n" +
	"\x10FederationReport\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\tR\x05hubId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x125\n" +
	"\x06leaves\x18\x03 \x03(\v2\x1d.opsagent.federation.LeafInfoR\x06leaves\x126\n" +
	"\x06groups\x18\x04 \x03(\v2\x1e.opsagent.federation.GroupInfoR\x06groups\x12D\n" +
	"\n" +
	"operations\x18\x05 \x03(\v2$.opsagent.federation.OperationStatusR\n" +
	"operations\"\x97\x02\n" +
	"\bLeafInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12A\n" +
	"\x06labels\x18\x02 \x03(\v2).opsagent.federation.LeafInfo.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06groups\x18\x03 \x03(\tR\x06groups\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x03R\blastSeen\x12%\n" +
	"\x0econfig_version\x18\x06 \x01(\tR\rconfigVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\tGroupInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fmember_count\x18\x02 \x01(\x05R\vmemberCount\x12!\n" +
	"\fonline_count\x18\x03 \x01(\x05R\vonlineCount\x12X\n" +
	"\x0ematch_criteria\x18\x04 \x03(\v21.opsagent.federation.GroupInfo.MatchCriteriaEntryR\rmatchCriteria\x1a@\n" +
	"\x12MatchCriteriaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x01\n" +
	"\x0fOperationStatus\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\ftarget_group\x18\x03 \x01(\tR\vtargetGroup\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\x05R\asuccess\x12\x16\n" +
	"\x06failed\x18\a \x01(\x05R\x06failed\x12\x18\n" +
	"\apending\x18\b \x01(\x05R\apending*=\n" +
	"\tAgentMode\x12\x13\n" +
	"\x0fMODE_STANDALONE\x10\x00\x12\f\n" +
	"\bMODE_HUB\x10\x01\x12\r\n" +
	"\tMODE_LEAF\x10\x022\xc7\x05\n" +
	"\x11FederationService\x12_\n" +
	"\bRegister\x12).opsagent.federation.FedAgentRegistration\x1a(.opsagent.federation.FedRegisterResponse\x12`\n" +
	"\tHeartbeat\x12(.opsagent.federation.FedHeartbeatRequest\x1a).opsagent.federation.FedHeartbeatResponse\x12X\n" +
	"\rReportMetrics\x12$.opsagent.federation.FedMetricReport\x1a!.opsagent.federation.FedMetricAck\x12j\n" +
	"\x13StreamConfigUpdates\x12+.opsagent.federation.FedConfigStreamRequest\x1a$.opsagent.federation.FedConfigUpdate0\x01\x12h\n" +
	"\x0eStreamCommands\x12,.opsagent.federation.FedCommandStreamRequest\x1a&.opsagent.federation.FedCommandRequest0\x01\x12f\n" +
	"\x13ReportCommandResult\x12%.opsagent.federation.FedCommandResult\x1a(.opsagent.federation.FedCommandResultAck\x12W\n" +
	"\fReportHealth\x12$.opsagent.federation.FedHealthReport\x1a!.opsagent.federation.FedHealthAckB6Z4github.com/cy77cc/opsagent/internal/federation/protob\x06proto3"

var (
	file_proto_federation_proto_rawDescOnce sync.Once
	file_proto_federation_proto_rawDescData []byte
)

func file_proto_federation_proto_rawDescGZIP() []byte {
	file_proto_federation_proto_rawDescOnce.Do(func() {
		file_proto_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_federation_proto_rawDesc), len(file_proto_federation_proto_rawDesc)))
	})
	return file_proto_federation_proto_rawDescData
}

var file_proto_federation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_federation_proto_goTypes = []any{
	(AgentMode)(0),                  // 0: opsagent.federation.AgentMode
	(*FedAgentRegistration)(nil),    // 1: opsagent.federation.FedAgentRegistration
	(*FedRegisterResponse)(nil),     // 2: opsagent.federation.FedRegisterResponse
	(*FedHeartbeatRequest)(nil),     // 3: opsagent.federation.FedHeartbeatRequest
	(*FedHeartbeatResponse)(nil),    // 4: opsagent.federation.FedHeartbeatResponse
	(*FedMetricReport)(nil),         // 5: opsagent.federation.FedMetricReport
	(*FedMetric)(nil),               // 6: opsagent.federation.FedMetric
	(*FedField)(nil),                // 7: opsagent.federation.FedField
	(*FedMetricAck)(nil),            // 8: opsagent.federation.FedMetricAck
	(*FedConfigStreamRequest)(nil),  // 9: opsagent.federation.FedConfigStreamRequest
	(*FedConfigUpdate)(nil),         // 10: opsagent.federation.FedConfigUpdate
	(*FedCommandStreamRequest)(nil), // 11: opsagent.federation.FedCommandStreamRequest
	(*FedCommandRequest)(nil),       // 12: opsagent.federation.FedCommandRequest
	(*FedCommandResult)(nil),        // 13: opsagent.federation.FedCommandResult
	(*FedCommandResultAck)(nil),     // 14: opsagent.federation.FedCommandResultAck
	(*FedHealthReport)(nil),         // 15: opsagent.federation.FedHealthReport
	(*FedHealthAck)(nil),            // 16: opsagent.federation.FedHealthAck
	(*FederationReport)(nil),        // 17: opsagent.federation.FederationReport
	(*LeafInfo)(nil),                // 18: opsagent.federation.LeafInfo
	(*GroupInfo)(nil),               // 19: opsagent.federation.GroupInfo
	(*OperationStatus)(nil),         // 20: opsagent.federation.OperationStatus
	nil,                             // 21: opsagent.federation.FedAgentRegistration.LabelsEntry
	nil,                             // 22: opsagent.federation.FedAgentRegistration.AutoLabelsEntry
	nil,                             // 23: opsagent.federation.FedHeartbeatRequest.LabelsEntry
	nil,                             // 24: opsagent.federation.FedMetric.TagsEntry
	nil,                             // 25: opsagent.federation.FedHealthReport.SubsystemStatusEntry
	nil,                             // 26: opsagent.federation.LeafInfo.LabelsEntry
	nil,                             // 27: opsagent.federation.GroupInfo.MatchCriteriaEntry
}
var file_proto_federation_proto_depIdxs = []int32{
	21, // 0: opsagent.federation.FedAgentRegistration.labels:type_name -> opsagent.federation.FedAgentRegistration.LabelsEntry
	22, // 1: opsagent.federation.FedAgentRegistration.auto_labels:type_name -> opsagent.federation.FedAgentRegistration.AutoLabelsEntry
	0,  // 2: opsagent.federation.FedAgentRegistration.mode:type_name -> opsagent.federation.AgentMode
	23, // 3: opsagent.federation.FedHeartbeatRequest.labels:type_name -> opsagent.federation.FedHeartbeatRequest.LabelsEntry
	6,  // 4: opsagent.federation.FedMetricReport.metrics:type_name -> opsagent.federation.FedMetric
	24, // 5: opsagent.federation.FedMetric.tags:type_name -> opsagent.federation.FedMetric.TagsEntry
	7,  // 6: opsagent.federation.FedMetric.fields:type_name -> opsagent.federation.FedField
	25, // 7: opsagent.federation.FedHealthReport.subsystem_status:type_name -> opsagent.federation.FedHealthReport.SubsystemStatusEntry
	18, // 8: opsagent.federation.FederationReport.leaves:type_name -> opsagent.federation.LeafInfo
	19, // 9: opsagent.federation.FederationReport.groups:type_name -> opsagent.federation.GroupInfo
	20, // 10: opsagent.federation.FederationReport.operations:type_name -> opsagent.federation.OperationStatus
	26, // 11: opsagent.federation.LeafInfo.labels:type_name -> opsagent.federation.LeafInfo.LabelsEntry
	27, // 12: opsagent.federation.GroupInfo.match_criteria:type_name -> opsagent.federation.GroupInfo.MatchCriteriaEntry
	1,  // 13: opsagent.federation.FederationService.Register:input_type -> opsagent.federation.FedAgentRegistration
	3,  // 14: opsagent.federation.FederationService.Heartbeat:input_type -> opsagent.federation.FedHeartbeatRequest
	5,  // 15: opsagent.federation.FederationService.ReportMetrics:input_type -> opsagent.federation.FedMetricReport
	9,  // 16: opsagent.federation.FederationService.StreamConfigUpdates:input_type -> opsagent.federation.FedConfigStreamRequest
	11, // 17: opsagent.federation.FederationService.StreamCommands:input_type -> opsagent.federation.FedCommandStreamRequest
	13, // 18: opsagent.federation.FederationService.ReportCommandResult:input_type -> opsagent.federation.FedCommandResult
	15, // 19: opsagent.federation.FederationService.ReportHealth:input_type -> opsagent.federation.FedHealthReport
	2,  // 20: opsagent.federation.FederationService.Register:output_type -> opsagent.federation.FedRegisterResponse
	4,  // 21: opsagent.federation.FederationService.Heartbeat:output_type -> opsagent.federation.FedHeartbeatResponse
	8,  // 22: opsagent.federation.FederationService.ReportMetrics:output_type -> opsagent.federation.FedMetricAck
	10, // 23: opsagent.federation.FederationService.StreamConfigUpdates:output_type -> opsagent.federation.FedConfigUpdate
	12, // 24: opsagent.federation.FederationService.StreamCommands:output_type -> opsagent.federation.FedCommandRequest
	14, // 25: opsagent.federation.FederationService.ReportCommandResult:output_type -> opsagent.federation.FedCommandResultAck
	16, // 26: opsagent.federation.FederationService.ReportHealth:output_type -> opsagent.federation.FedHealthAck
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_federation_proto_init() }
func file_proto_federation_proto_init() {
	if File_proto_federation_proto != nil {
		return
	}
	file_proto_federation_proto_msgTypes[6].OneofWrappers = []any{
		(*FedField_DoubleValue)(nil),
		(*FedField_IntValue)(nil),
		(*FedField_StringValue)(nil),
		(*FedField_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_federation_proto_rawDesc), len(file_proto_federation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_federation_proto_goTypes,
		DependencyIndexes: file_proto_federation_proto_depIdxs,
		EnumInfos:         file_proto_federation_proto_enumTypes,
		MessageInfos:      file_proto_federation_proto_msgTypes,
	}.Build()
	File_proto_federation_proto = out.File
	file_proto_federation_proto_goTypes = nil
	file_proto_federation_proto_depIdxs = nil
}
